### ISSUE TITLE
File hexdump diff output can generate gigantic files and slow down build process

### ISSUE THREAD

**Issue by lachs0r** [openSUSE/build-compare#24]
https://github.com/openSUSE/build-compare/blob/4639e303a98be9fa8eb777dfaa67da5b36d49831/pkg-diff.sh#L297-L300

See issue title. Basically large packages can generate unreasonably large hexdumps that nobody will ever look at anyway. Ran into issues with workers taking dozens of gigabytes of space and waste 99% of the build time just grinding diff.

**Comment by coolo** [comment]
I wouldn't say that noone looks at it - but possibly we should write a little C program that does the hexdump diff of 2 files in one go without tempory files.

**Comment by lachs0r** [comment]
Well I meant: 50 GiB of hexdump and a gigantic diff piped through head isn’t going to be particularly useful :D

Maybe use shell process substitution as a temporary measure to at least avoid writing all that to disk?

**Comment by coolo** [comment]
implementing what is wanted in C is about 30 lines I'd guess :)

**Comment by olafhering** [comment]
Thanks for the report. A fifo should be used to avoid the temporary files.

Not sure why diff(1) would run OOM.

**Comment by olafhering** [comment]
This will run OOM, diff just reads from fd 3 and never considers fd 4:
````
#!/bin/bash
set -ex
export TMPDIR=`mktemp --directory --tmpdir=/dev/shm XXX`
trap "rm -rfv \"$TMPDIR\"" EXIT
pushd $TMPDIR
mkfifo -m 0600 po
mkfifo -m 0600 pn
hexdump /dev/urandom > po &
hexdump /dev/urandom > pn &
diff po pn | head -n 2
````

There is apparently no option for diff to read chunks from both sides.

As a first step such approach is likely ok because it avoids the need for potentially large temporary files.

What files are so large that they produce GB of hexdump output, which will potentially lead to OOM of diff either way?

One way to solve it in bash is to use cmp -b, parse the output to find the offset, then use hexdump -s N -l N to show only the first chunk of difference. That way the usage of head -n N can be reduced as well, which would also gives the benefit that ^+ lines are shown.
Hopefully cmp -b and hexdump -s/-l is available everywhere...
